[package]
name = "maybe-const-fn"
version = "0.1.0"
description = "Macro to make a function as `const` based on a cfg flag"
authors = ["Techcable"]
categories = [
    "development-tools::build-utils",
    "no-std",
    "no-std::no-alloc",
    "rust-patterns",
]
keywords = ["const", "rustversion"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Techcable/maybe-const-fn.rs"
# 1.31 - First version supporting Rust 2018
rust-version = "1.31"
